# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRGvXPuxYtG11qn-maPuzXRtNXz2HvmM
"""

"""
SILICON DIODE I-V CHARACTERISTICS
=================================

What you're building: a model of how current flows through a silicon diode as
you change the voltage across it, how that changes with temperature, and what
happens when you account for the resistance of the silicon itself.

At the end you'll have a plot and one real quantitative result: the forward
voltage of a silicon diode drops about 2 mV for every degree Celsius of
warming. That number is in every semiconductor textbook. You'll derive it.

HOW TO USE THIS FILE
  1. Run it now:  python diode_iv.py
     It will tell you which step to do next.
  2. Fill in one TODO at a time. Run again after each.
  3. The self-check at the bottom tells you if your physics is right.

    pip install numpy matplotlib
"""

import numpy as np
import matplotlib.pyplot as plt


# ---------------------------------------------------------------------------
# PHYSICAL CONSTANTS  (given -- nothing to do here)
# ---------------------------------------------------------------------------

q  = 1.602176634e-19   # elementary charge, coulombs
k  = 1.380649e-23      # Boltzmann constant, J/K
EG = 1.12              # silicon bandgap, electron-volts

IS_REF = 1e-12         # saturation current at reference temp, amps
T_REF  = 300.0         # reference temperature, kelvin
N      = 1.0           # ideality factor (1 = ideal, real diodes run 1-2)


# ---------------------------------------------------------------------------
# STEP 1 -- Thermal voltage
# ---------------------------------------------------------------------------
def thermal_voltage(T):
    """
    The thermal voltage V_T sets the scale for how sharply current rises
    with applied voltage. It's the natural voltage unit of a semiconductor.

        V_T = k * T / q

    T is in kelvin. Returns volts.

    Sanity target: about 0.02585 V at T = 300 K (roughly 26 mV).
    """
    return k * T / q



# ---------------------------------------------------------------------------
# STEP 2 -- The ideal diode (Shockley) equation
# ---------------------------------------------------------------------------
def current(V, T=T_REF, n=N, Is=None):
    """
    The Shockley equation. Current rises EXPONENTIALLY with voltage, which is
    why a diode conducts almost nothing below ~0.6 V and then turns on hard.

        I = Is(T) * ( exp( V / (n * V_T) ) - 1 )

    Is defaults to the temperature-dependent saturation current, so raising T
    correctly increases current. Pass Is explicitly to override.
    """
    VT = thermal_voltage(T)
    if Is is None:
        Is = saturation_current(T, n)
    return Is * (np.exp(V / (n * VT)) - 1)


# ---------------------------------------------------------------------------
# STEP 3 -- How saturation current depends on temperature
# ---------------------------------------------------------------------------
def saturation_current(T, n=N):
    """
    This is where the temperature effect actually lives. Is is tiny, but it
    grows very fast with temperature, because thermal energy frees more
    carriers across the bandgap.

        Is(T) = IS_REF * (T/T_REF)^3 * exp[ (EG*q / (n*k)) * (1/T_REF - 1/T) ]

    Note EG is in electron-volts, so multiply by q to get joules.

    Sanity target: Is at 350 K should be several hundred times Is at 300 K.
    """
    # TODO 3:
    return IS_REF * (T / T_REF) ** 3 * np.exp((EG * q / (n * k)) * (1 / T_REF - 1 / T))



# ---------------------------------------------------------------------------
# STEP 4 -- Voltage needed to push a given current (with series resistance)
# ---------------------------------------------------------------------------
def voltage_for_current(I, T=T_REF, n=N, Rs=0.0):
    r"""
    Real diodes have resistance in the silicon and the leads. That resistance
    adds a voltage drop I*Rs on top of the junction voltage, which makes the
    curve bend over at high current instead of rising forever.

    Solving I -> V is easy (invert the Shockley equation). Solving V -> I with
    Rs is not, because I appears on both sides. So we sweep current instead.

        V = n * V_T * ln( I / Is(T) + 1 )  +  I * Rs
              \_______ junction _______/     \_ohmic_/

    Sanity target: at 1 A and 300 K with Rs = 0, V should be about 0.71 V.
    """
    VT = thermal_voltage(T)
    Is = saturation_current(T, n)
    # TODO 4:
    return n * VT * np.log(I / Is + 1) + I * Rs



# ---------------------------------------------------------------------------
# ANALYSIS -- extract the temperature coefficient  (given, no TODO)
# ---------------------------------------------------------------------------
def temperature_coefficient(I_fixed=0.010, temps=(275, 300, 325, 350)):
    """
    Hold current fixed, measure the forward voltage at several temperatures,
    fit a straight line. The slope is your result, in mV per kelvin.
    """
    T = np.array(temps, dtype=float)
    V = np.array([voltage_for_current(I_fixed, t) for t in T])
    slope, intercept = np.polyfit(T, V, 1)
    return slope * 1000, T, V


# ---------------------------------------------------------------------------
# PLOTS  (given -- these work once your functions are filled in)
# ---------------------------------------------------------------------------
def make_plots():
    fig, ax = plt.subplots(1, 3, figsize=(15, 4.4))

    # (a) the classic I-V turn-on curve
    V = np.linspace(0, 0.8, 400)
    ax[0].plot(V, current(V) * 1000, lw=2, color="#1B4D3E")
    ax[0].set_xlabel("Voltage (V)"); ax[0].set_ylabel("Current (mA)")
    ax[0].set_title("Ideal diode at 300 K"); ax[0].set_ylim(0, 50)
    ax[0].grid(alpha=.3)

    # (b) the same curve at several temperatures
    for T, c in zip([275, 300, 325, 350], ["#2C5F8A", "#1B4D3E", "#C4772F", "#8C3A2B"]):
        ax[1].plot(V, current(V, T) * 1000, lw=2, color=c, label=f"{T:.0f} K")
    ax[1].set_xlabel("Voltage (V)"); ax[1].set_ylabel("Current (mA)")
    ax[1].set_title("Warmer diode turns on sooner")
    ax[1].set_ylim(0, 50); ax[1].legend(); ax[1].grid(alpha=.3)

    # (c) what series resistance does at high current
    I = np.logspace(-6, 0.3, 300)
    for Rs, c in zip([0.0, 0.1, 0.5], ["#1B4D3E", "#C4772F", "#8C3A2B"]):
        ax[2].plot(voltage_for_current(I, Rs=Rs), I, lw=2, color=c,
                   label=f"Rs = {Rs} $\\Omega$")
    ax[2].set_yscale("log")
    ax[2].set_xlabel("Voltage (V)"); ax[2].set_ylabel("Current (A, log)")
    ax[2].set_title("Series resistance bends the curve")
    ax[2].legend(); ax[2].grid(alpha=.3, which="both")

    plt.tight_layout()
    plt.savefig("diode_iv.png", dpi=150)
    plt.show()
    print("  saved plot -> diode_iv.png")


# ---------------------------------------------------------------------------
# SELF-CHECK -- tells you what to do next
# ---------------------------------------------------------------------------
def check():
    print("\nSILICON DIODE I-V\n" + "=" * 52)

    vt = thermal_voltage(300.0)
    if vt is None:
        print("  NEXT: TODO 1 in thermal_voltage()."); return False
    ok = abs(vt - 0.02585) < 0.0002
    print(f"  [{'ok' if ok else 'XX'}] thermal voltage @300K = {vt*1000:.2f} mV  (expect ~25.85)")
    if not ok: print("       check: V_T = k*T/q"); return False

    i0, i7 = current(0.0), current(0.7)
    if i0 is None:
        print("  NEXT: TODO 2 in current()."); return False
    ok = abs(i0) < 1e-18 and 0.001 < i7 < 10
    print(f"  [{'ok' if ok else 'XX'}] I(0V) = {i0:.2e} A, I(0.7V) = {i7*1000:.1f} mA")
    if not ok: print("       check: the  -1  term, and V/(n*V_T) in the exponent"); return False

    s3, s35 = saturation_current(300.0), saturation_current(350.0)
    if s3 is None:
        print("  NEXT: TODO 3 in saturation_current()."); return False
    ok = abs(s3 - IS_REF) / IS_REF < 0.01 and 100 < s35 / s3 < 5000
    print(f"  [{'ok' if ok else 'XX'}] Is @300K = {s3:.2e} A, grows {s35/s3:.0f}x by 350 K")
    if not ok: print("       check: EG is in eV -- multiply by q for joules"); return False

    v1 = voltage_for_current(1.0)
    if v1 is None:
        print("  NEXT: TODO 4 in voltage_for_current()."); return False
    ok = abs(v1 - 0.714) < 0.02
    print(f"  [{'ok' if ok else 'XX'}] V at 1 A, Rs=0 = {v1:.3f} V  (expect ~0.714)")
    if not ok: print("       check: n*V_T*ln(I/Is + 1) + I*Rs"); return False

    print("\n  All four steps correct. Result:\n")
    slope, T, V = temperature_coefficient()
    for t, v in zip(T, V):
        print(f"    {t:5.0f} K ({t-273.15:5.1f} C)   Vf = {v:.4f} V")
    print(f"\n    dVf/dT = {slope:.3f} mV/K")
    print(f"    Textbook value for silicon: about -2 mV/K")
    print(f"    {'MATCH.' if abs(slope + 2) < 0.3 else 'Off -- recheck step 3.'}")

    make_plots()
    print("\n  Write up what you found in README.md and push to GitHub.\n")
    return True


if __name__ == "__main__":
    check()
